//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.19 at 04:58:16 PM CET 
//


package dictionary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="english-word" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="german-word" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "englishWord",
    "germanWord"
})
@XmlRootElement(name = "word")
public class Word {

    @XmlElement(name = "english-word", required = true)
    protected String englishWord;
    @XmlElement(name = "german-word", required = true)
    protected String germanWord;

    /**
     * Gets the value of the englishWord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishWord() {
        return englishWord;
    }

    /**
     * Sets the value of the englishWord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishWord(String value) {
        this.englishWord = value;
    }

    /**
     * Gets the value of the germanWord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGermanWord() {
        return germanWord;
    }

    /**
     * Sets the value of the germanWord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGermanWord(String value) {
        this.germanWord = value;
    }

}
